server:
  port: 8001

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000

secure:
  ignore:
    urls:
      - /token/*
      - /css/**
      - /error

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: c9c245b4-d275-465b-aa9b-7ee10655d14f

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/admin_oauth2?setUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: SELECT 1

  data:
    redis:
      client-type: lettuce
      cluster:
        max-redirects: 5
        nodes:
          - redis:6379
          - redis:6380
          - redis:6381
          - redis:6382
          - redis:6383
          - redis:6384
      timeOut: 6000
      database: 1
      lettuce:
        pool:
          max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认 8
          max-idle: 8 #连接池中的最大空闲连接 默认 8
          max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          min-idle: 0 #连接池中的最小空闲连接 默认 0

mybatis:
  type-aliases-package: com.vip.microservice.oauth2.model.domain
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback-spring.xml